version: '3.7'
services:
  gerocuidado-forum-api:
    image: gerocuidadodev/node:18.17.0-alpine-dev
    container_name: gerocuidado-forum-api
    volumes:
      - '.:/home/node/app'
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - NODE_ENV=development
    ports:
      - '3002:3002'
      - '7002:7002'
    depends_on:
      - gerocuidado-forum-db
    networks:
      - gerocuidado-apis-net # Rede compartilhada entre as APIs

  gerocuidado-forum-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    container_name: gerocuidado-forum-db
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - './db/postgres:/var/lib/postgresql/data'
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-forum-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5002:5002'
    networks:
      - gerocuidado-apis-net # Rede compartilhada entre as APIs

networks:
  gerocuidado-apis-net:
    external: true # Rede compartilhada com outras APIs
